#!/usr/bin/env python
##
#
#  @package pyselenium
#  @file    pyyelenium01_test.py
#  @author  Rolf Hemmerling
#  @date    2014-01-06
#
#  This file was originally generated by PyScripter's unitest wizard
#

import unittest
#from pyselenium01 import PySelenium01
from selenium import webdriver
from selenium.webdriver.common.keys import Keys


def dummy():
    """ Dummy function for comparison of the return values """
    return

class PySelenium01Test(unittest.TestCase):

    def setUp(self):
        self.browser = webdriver.Firefox()
        self.addCleanup(self.browser.quit)
        return

    def tearDown(self):
        #self.browser.close()
        return

    def testMain(self):
        self.browser.get('http://www.facebook.com')
        assert "Facebook" in self.browser.title
        elem = self.browser.find_element_by_name("email")
        elem.send_keys("hemmerling@gmx.net")
        elem = self.browser.find_element_by_name("pass")
        elem.send_keys("metting885516")
        elem.send_keys(Keys.RETURN)
        assert "Facebook" in self.browser.title
        return

# run all tests
if __name__ == "__main__":
    try:
        unittest.main()
    except SystemExit as inst:
        if inst.args[0] is True: # raised by sys.exit(True) when tests failed
            raise

