#This file was originally generated by PyScripter's unitest wizard

import unittest
from cell import Cell
from cell_list import CellList

def dummy():
    """ Dummy function for comparison of the return values """
    return

class Gol01Test(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCellAppend(self):
        self.cell11 = Cell()
        self.cell11.set_coordinates(1,1)
        self.cell_list = CellList()
        self.cell_list.append(self.cell11)
        result = self.cell_list.exist(1,1)
        assert result == True, 'Gol01.get_size() does not provide the right return value'
        pass

    def testCellRemove(self):
        pass

# run all tests
if __name__ == "__main__":
    try:
        unittest.main()
    except SystemExit as inst:
        if inst.args[0] is True: # raised by sys.exit(True) when tests failed
            raise

